# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.cache/wt [current_project]
set_property parent.project_path C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/Seven_RegLED.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/Display.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/Light.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/clock.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/jump.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/regfile.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/ControlUnit.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/signExtend.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/ROM.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/RAM.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/pcAddImm.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/pcAddFour.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/pc.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/dataSelect_5_Bit.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/dataSelect_32_Bit.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/dataSelect_321.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/ALU.v
  C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/sources_1/new/Top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/constrs_2/new/cpu_cst.xdc
set_property used_in_implementation false [get_files C:/Users/DELL/Desktop/mips_cpu_32basys/mips_cpu_32.srcs/constrs_2/new/cpu_cst.xdc]


synth_design -top Top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
