set_property IOSTANDARD LVCMOS33 [get_ports {Xianshing[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Xianshing[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Xianshing[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Xianshing[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Xianshism[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Xianshism[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Xianshism[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Xianshism[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Xianshism[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Xianshism[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Xianshism[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Xianshism[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports bntr]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports sw14]
set_property IOSTANDARD LVCMOS33 [get_ports sw15]
set_property PACKAGE_PIN W4 [get_ports {Xianshing[3]}]
set_property PACKAGE_PIN V4 [get_ports {Xianshing[2]}]
set_property PACKAGE_PIN U4 [get_ports {Xianshing[1]}]
set_property PACKAGE_PIN U2 [get_ports {Xianshing[0]}]
set_property PACKAGE_PIN V8 [get_ports {Xianshism[3]}]
set_property PACKAGE_PIN U8 [get_ports {Xianshism[2]}]
set_property PACKAGE_PIN W6 [get_ports {Xianshism[1]}]
set_property PACKAGE_PIN W7 [get_ports {Xianshism[0]}]
set_property PACKAGE_PIN T17 [get_ports bntr]
set_property PACKAGE_PIN W2 [get_ports Reset]
set_property PACKAGE_PIN R3 [get_ports RST]
set_property PACKAGE_PIN R2 [get_ports sw14]
set_property PACKAGE_PIN T1 [get_ports sw15]


set_property PACKAGE_PIN W5 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]



set_property PACKAGE_PIN U5 [get_ports {Xianshism[4]}]
set_property PACKAGE_PIN V5 [get_ports {Xianshism[5]}]
set_property PACKAGE_PIN U7 [get_ports {Xianshism[6]}]
set_property PACKAGE_PIN V7 [get_ports {Xianshism[7]}]
